### PR TITLE
57 signup and log in backend and front end

### PR DESCRIPTION
**Pull request by jqueja**
Finished the Signup page.

1) Email validation sends email to the user
2) /info page works with the API endpoint in the backend

Changed the public_profile to users to simplify tables.

### CODE REVIEW

**Comment by Parshana007** [comment]
- looks great
- just in case I would double create a couple of cases throw errors in each of the signup and login pages in the backend files such that if for some reason it couldn't insert the row to send an error message
- other than that looks good and concise

**Comment by joanna-chou** [comment]
Looks good! Good job on connection of endpoints and to database. We will figure out how to connect workout logs with user ids and display on frontend next pull.

**Comment by jqueja** [comment]
> Not sure what else to say besides it looks great!

Thank you so much for your kind words!

**Comment by jqueja** [comment]
> * just in case I would double create a couple of cases throw errors in each of the signup and login pages in the backend files such that if for some reason it couldn't insert the row to send an error message
> * make sure not to commit the binary files
> * other than that looks good and concise

Uncommitted the binary files and got it working on adding more logical steps in the back end.

**Comment by jqueja** [comment]
> Looks good! Good job on connection of endpoints and to database. We will figure out how to connect workout logs with user ids and display on frontend next pull.

Thank you! Passing in the unique id through navigate.

**Pull request merged**
